common:
  random_seed: 42
  grid:
    n_rows: 50 # It must be adjusted to the final map
    n_cols: 50 # It must be adjusted to the final map
    px_rows: 500
    px_cols: 700
  initially_infected_population: 0.1
  infection_probabilities:
    - 0.3
    - 0.1

environment:
  store:
    map_path: 'map.npy'
    entrance_cells:
      - [10, 10]
      - [10, 10]
  park:
    map_path: 'map.npy'
    entrance_cells:
      - [10, 10]
      - [10, 10]
  forest:
    map_path: 'map.npy'
    entrance_cells:
      - [10, 10]
      - [10, 10]

agent:
  infected:
    shape: "covid_agent_simulation/resources/sick.png"
    color: null
  healthy:
    shape: "covid_agent_simulation/resources/mario.png"
    color: null
  recovered:
    shape: "covid_agent_simulation/resources/recovered.png"
    color: null

patch:
  home:
    shape: "covid_agent_simulation/resources/wall.png"
    color: null
  park:
    shape: "covid_agent_simulation/resources/grass.png"
    color: null