common:
  random_seed: 42
  grid:
    px_rows: 500
    px_cols: 900
  initially_infected_population: 0.2
  initially_recovered_population: 0.1
  infection_probabilities:
    - 0.2
    - 0.05

environment:
  store:
    map_path: 'map.npy'
    num_agents_allowed: 5
    num_target_cells: 3
    entrance_cells:
      - [25, 55]
  park:
    map_path: 'map.npy'
    num_agents_allowed: 5
    num_target_cells: 8
    entrance_cells:
      - [25, 55]
      - [25, 55]
  forest:
    map_path: 'map.npy'
    num_agents_allowed: 15
    num_target_cells: 30
    entrance_cells:
      - [25, 55]
      - [25, 55]

agent:
    infected:
      shape: "circle"
      color: "red"
    healthy:
      shape: "circle"
      color: "green"
    recovered:
      shape: "circle"
      color: "blue"

patch:
  home:
    shape: "rect"
    color: "yellow"
  park:
    shape: "rect"
    color: "green"
