common:
  random_seed: 42
  grid:
    rows: 50
    cols: 80
    px_rows: 500
    px_cols: 900
  initially_infected_population: 0.1
  initially_recovered_population: 0.1
  infection_probabilities:
    - 0.5
    - 0.2

environment:
  store:
    map_path: 'store_map.npy'
    num_agents_allowed: 5
    max_time_outside: 15
    num_target_cells: 3
    entrance_cells:
      - [35, 66]
  park:
    map_path: 'park_map.npy'
    num_agents_allowed: 5
    max_time_outside: 15
    num_target_cells: 8
    entrance_cells:
      - [35, 66]
      - [34, 42]
  forest:
    map_path: 'forest_map.npy'
    num_agents_allowed: 5
    max_time_outside: 15
    num_target_cells: 30
    entrance_cells:
      - [35, 66]
      - [34, 42]
      - [14, 68]

agent:
  infected:
    shape: "covid_agent_simulation/resources/icon-infected.png"
    color: null
  healthy:
    shape: "covid_agent_simulation/resources/icon-healthy.png"
    color: null
  recovered:
    shape: "covid_agent_simulation/resources/icon-cured.png"
    color: null

patch:
  home:
    shape: "rect"
    color: "yellow"
  park:
    shape: "rect"
    color: "green"
