common:
  random_seed: 42
  grid:
    n_rows: 20 # It must be adjusted to the final map
    n_cols: 20 # It must be adjusted to the final map
    px_rows: 500
    px_cols: 700
  initially_infected_population: 0.01
  infection_probabilities:
    - 0.1
    - 0.02

environment:
  store:
    map_path: 'map.npy'
    num_agents_allowed: 5
    num_target_cells: 3
    entrance_cells:
      - [13, 11]
  park:
    map_path: 'map.npy'
    num_agents_allowed: 10
    num_target_cells: 8
    entrance_cells:
      - [10, 10]
      - [10, 10]
  forest:
    map_path: 'map.npy'
    num_agents_allowed: 15
    num_target_cells: 30
    entrance_cells:
      - [10, 10]
      - [10, 10]

agent:
    infected:
      shape: "circle"
      color: "red"
    healthy:
      shape: "circle"
      color: "green"
    recovered:
      shape: "circle"
      color: "blue"

patch:
  home:
    shape: "rect"
    color: "yellow"
  park:
    shape: "rect"
    color: "green"